services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      - CLICKHOUSE_USER=admin
      - CLICKHOUSE_PASSWORD=secret_pw
      - CLICKHOUSE_DB=indicadores
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ingest:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    container_name: enemdu_ingest
    depends_on:
      clickhouse:
        condition: service_healthy
    volumes:
      - ./data:/data:ro
      - ./logs:/logs:ro
      - ./errors:/errors:ro
      - ./init-scripts:/init-scripts:ro
    environment:
      - CH_HOST=clickhouse
      - CH_PORT=9000
      - CH_USER=admin
      - CH_PASSWORD=secret_pw
      - CH_DATABASE=indicadores
    command: ["sh", "-c", "
        python ingest_codigos.py && \
        python ingest_vivienda.py && \
        python ingest_persona.py"]

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_SECRET_KEY=your_superset_secret
      - DATABASE_DIALECT=clickhouse
      - DATABASE_HOST=clickhouse
      - DATABASE_PORT=8123
      - DATABASE_DB=indicadores
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=secret_pw
    ports:
      - "8088:8088"
    depends_on:
      - clickhouse
    volumes:
      - superset_home:/home/superset
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        pip install clickhouse-sqlalchemy clickhouse-driver "sqlalchemy==1.4.54" clickhouse-connect && \
        superset fab create-admin \
          --username admin \
          --firstname Admin \
          --lastname User \
          --email admin@example.com \
          --password admin && \
        superset db upgrade && \
        superset init && \
        exec superset run -h 0.0.0.0 -p 8088
  indicadores:
    build:
      context: ./ingest
      dockerfile: Dockerfile
    container_name: indicadores_enemdu
    depends_on:
      clickhouse:
        condition: service_healthy
      enemdu_ingest:
        condition: service_completed_successfully
    volumes:
      - ./data:/data:ro
      - ./data/resultados:/data/resultados:rw
    environment:
      - CH_HOST=clickhouse
      - CH_PORT=9000
      - CH_USER=admin
      - CH_PASSWORD=secret_pw
      - CH_DATABASE=indicadores
    command: ["python", "calcular_indicadores.py"]


volumes:
  clickhouse_data:
  superset_home:
